version: "3.9"

services:
  postgres_test:
    image: postgres:15
    container_name: costa_test_db
    restart: always
    environment:
      POSTGRES_USER: costa_user
      POSTGRES_PASSWORD: supersecretpassword
      POSTGRES_DB: costadb_test
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U costa_user"]
      interval: 2s
      timeout: 2s
      retries: 10
